<?php

namespace AppBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindOne($id)
    {
        return $this
            ->createQueryBuilder('o')
            ->where('o.product = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

    public function OrdersByUsers($id)
    {
        return $this
            ->createQueryBuilder('o')
            ->leftJoin('o.product', 'p')
            ->addSelect('p')
            ->where('o.buyer = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult()
            ;
    }
}
