<?php

namespace AppBundle\Repository;

/**
 * productRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productRatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function countRateProduct($id)
    {
        return $this
            ->createQueryBuilder('r')
            ->select('COUNT(r) AS NB,avg(r.rate) AS AVG ')
            ->where('r.product = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult()
            ;
    }
}
