<?php

namespace AppBundle\Repository;

/**
 * UserRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
